### PR TITLE
add contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
Added  the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

### CODE REVIEW

**Comment by khareyash05** [comment]
@gokulprathin8  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Comment by khareyash05** [comment]
@gokulprathin8 Gentle reminder!

**Comment by khareyash05** [comment]
Hi! @gokulprathin8 Due to the space between Level and 0 this PR isnt being counted
Kindly delete the space
Thanx
image

**Comment by gokulprathin8** [comment]
@khareyash05 , its Fixed

**Comment by khareyash05** [comment]
Thanx

**Pull request merged**
